language: php

sudo: false

php:
  - 7.1
  - 7.2
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-source --no-interaction --dev

script: composer tests
